language: python
matrix:
  include:
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
before_install:
  - pip install poetry
install:
  - poetry config virtualenvs.create false
  # Poetry 1.1.0 added parallel installation as an option;
  # unfortunately it seems to have some issues with installing/updating "requests" and "certifi"
  # while simultaneously atttempting to *use* those packages to install other packages.
  # For now we disable it.
  - poetry config installer.parallel false
  - poetry install --no-ansi
script:
  - poetry run pytest
